"""add unique

Revision ID: 9c07140a2d00
Revises: 8b4c5dcedf2e
Create Date: 2026-04-27 17:44:38.802015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c07140a2d00'
down_revision: Union[str, Sequence[str], None] = '8b4c5dcedf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_product_date', 'spimex_trading_results', ['exchange_product_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_product_date', 'spimex_trading_results', type_='unique')
    # ### end Alembic commands ###
