"""init schema

Revision ID: d6b1697e92e2
Revises: 
Create Date: 2026-05-05 14:00:41.499309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6b1697e92e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spimex_trading_results', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index('index_date', 'spimex_trading_results', ['date'], unique=False)
    op.create_index('index_date_filters', 'spimex_trading_results', ['date', 'oil_id'], unique=False)
    op.create_index('index_filters', 'spimex_trading_results', ['oil_id', 'delivery_type_id', 'delivery_basis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_filters', table_name='spimex_trading_results')
    op.drop_index('index_date_filters', table_name='spimex_trading_results')
    op.drop_index('index_date', table_name='spimex_trading_results')
    op.alter_column('spimex_trading_results', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
