# Generated by Django 6.0.4 on 2026-04-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videoapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
